### ISSUE TITLE
Copying big dataset from Result View freezes the app

### ISSUE THREAD

**Issue by shytikov** [rappen/FetchXMLBuilder#209]
It seems copying big amount of data is done synchronously in `FXB`, thus the app freezes when `Ctrl+C`, in addition I have seen following error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.DataGridView.ProcessInsertKey(Keys keyData)
   at System.Windows.Forms.DataGridView.ProcessDataGridViewKey(KeyEventArgs e)
   at System.Windows.Forms.DataGridView.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.DataGridView.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2650.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2018.4.22
    Win32 Version: 1.2018.4.22
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2017.7.10
    Win32 Version: 1.2017.7.10
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.1.7600.16394
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/Microsoft.IdentityModel.DLL
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2017.10.7
    Win32 Version: 1.2017.10.7
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.12.0.817
    Win32 Version: 2.12.0.817
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/NuGet.Core.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2018.4.16
    Win32 Version: 1.2018.4.16
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2018.4.16
    Win32 Version: 1.2018.4.16
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.9002.0
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.9002.0
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.0.2090
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.882
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 2.29.0.1078
    Win32 Version: 2.29.40822.1520
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
    Assembly Version: 2.29.0.1078
    Win32 Version: 2.29.40822.1520
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Workspace/tmp/XrmToolBox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly Version: 1.2018.4.2
    Win32 Version: 1.2018.04.002
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2018.3.5
    Win32 Version: 1.2018.3.5
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2018.3.3
    Win32 Version: 1.2018.3.3
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2018.3.8
    Win32 Version: 1.2018.3.8
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2018.3.2
    Win32 Version: 1.2018.3.2
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2017.11.6
    Win32 Version: 1.2017.11.6
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
    Assembly Version: 1.2018.4.1
    Win32 Version: 1.2018.4.1
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2018.4.3
    Win32 Version: 1.2018.4.3
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2017.12.3
    Win32 Version: 1.2017.12.3
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2018.1.8
    Win32 Version: 1.2018.1.8
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2018.3.7
    Win32 Version: 1.2018.3.7
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2018.3.6
    Win32 Version: 1.2018.3.6
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly Version: 1.2017.7.3
    Win32 Version: 1.2017.7.3
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2017.12.6
    Win32 Version: 1.2017.12.6
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2018.1.2
    Win32 Version: 1.2018.1.2
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2017.4.10
    Win32 Version: 1.2017.4.10
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2016.6.3
    Win32 Version: 1.2016.6.3
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2018.4.6
    Win32 Version: 1.2018.4.6
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2017.8.6
    Win32 Version: 1.2017.8.6
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2017.4.4
    Win32 Version: 1.2017.4.4
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly Version: 1.2018.3.17
    Win32 Version: 1.2018.3.17
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
Xrm.Sdk.PluginRegistration
    Assembly Version: 3.2017.8.1
    Win32 Version: 3.2017.08.001
    CodeBase: file:///C:/USERS/ALEXEY.SHYTIKOV/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRM.SDK.PLUGINREGISTRATION.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
MetadataViewProxies_1f3d4c72-663e-4579-9e46-2984a7bc603e
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
System.IdentityModel.Selectors
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2650.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by rappen** [comment]
Waiting for your PR to fix this, @shytikov 😉

**Comment by rappen** [comment]
I tested both to select all and copy and paste, and using the new feature to open it in Excel. It takes a bit of time, but no error, everything looks good.
80k records, 35 columns.

I'm closing this now, if you still see problems, just reopen this issue! @shytikov
