### ISSUE TITLE
Crash on execute of FetchXML - invalid character in dictionary 2

### ISSUE THREAD

**Issue by partridgetim** [rappen/FetchXMLBuilder#263]
When executing any FetchXML query the plugin is crashing with exception 

**Invalid name character in 'Dictionary`2'.**

![image](https://user-images.githubusercontent.com/3292237/66051330-c0db4d80-e4fc-11e9-8441-e502cad0a3d5.png)

Details:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid name character in 'Dictionary`2'.
   at System.Xml.XmlTextWriter.ValidateName(String name, Boolean isNCName)
   at System.Xml.XmlTextWriter.WriteQualifiedName(String localName, String ns)
   at System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedName(String attrPrefix, XmlDictionaryString attrName, XmlDictionaryString attrNs, XmlDictionaryString name, XmlDictionaryString ns)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo(XmlWriterDelegator writer, XmlDictionaryString dataContractName, XmlDictionaryString dataContractNamespace)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo(XmlWriterDelegator writer, DataContract contract, DataContract declaredContract)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.<>c__DisplayClass111_0.<RetrieveMultiple>b__1(RunWorkerCompletedEventArgs completedargs)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

It does not seem to matter which entity I am querying or which attributes. I am using the latest XrmToolBox (version 1.2019.7.34) and the latest FetchXML Builder (version 1.2019.9.1). I have even downloaded a fresh copy of XrmToolBox and FetchXML Builder. I have tried running it normally as my user, or "run as adminstrator". I have verified that the FetchXML is correct by successfully executing it using FetchXML Tester.

**Comment by rappen** [comment]
This seems super strange. There is obviously nothing wrong with the query,
Something explodes during evaluation of the XML it seems. 
I have to try to get advise from some friends out there: @daryllabar @jamesnovak @shytikov perhaps...?

**Comment by rappen** [comment]
@partridgetim if possible I'd like you to test a few things:
From another computer?
Against another Dynamics organization?
With another output format?

![image](https://user-images.githubusercontent.com/2572253/66073366-35db7100-e557-11e9-9389-741060b652db.png)

**Comment by partridgetim** [comment]
Good idea. Now we're getting somewhere. I can reproduce when I point to another CRM org and on another machine. The error only occurs when the result view is serialized EntityCollection. I checked the following and they all work:
- View
- Serialized Explicit XML
- Serialized Basic XML
- Serialized JSON
- Raw fetch result
It does not matter if I select Retrieve all pages or not.

**Comment by daryllabar** [comment]
Are you running with some sort of extra windows security.  Serialization fails when running in an app domain that prevents reflection.

**Comment by jamesnovak** [comment]
Looks like a code issue. I can repro with the Entity Collection as Tim described!

**Comment by jamesnovak** [comment]
> Are you running with some sort of extra windows security. Serialization fails when running in an app domain that prevents reflection.

I learned something new today...

**Comment by rappen** [comment]
I get the same error for Serialized EntityCollection.
Ok, this is now something I can work with.

I haven't actually used that format for years, if ever. But I'm really curious what's you use case, why this format is the best for you?

**Comment by daryllabar** [comment]
@Jamesnovak it applies primarily to sandboxed plugins/workflows.  I had to write my own serialization library to get around it, back in the day.

**Comment by rappen** [comment]
@daryllabar ...which is exactly what the other serialization options in FXB are... :)

**Comment by rappen** [comment]
"Solved" as a result of #327
