### ISSUE TITLE
Exception when coming from Shuffle builder - clicking on Select Attribute

### ISSUE THREAD

**Issue by imranakram** [rappen/FetchXMLBuilder#274]
I was trying the FetchXml feature on Shuffle builder. 

- Chose contact entity in shuffle block for export 
- Went on to create FetchXml which pre-selects contact entity
- Click on `Select Attribute` which results in this exception:- 

`
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.SelectAttributes()
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.HandleNodeMenuClick(String ClickedTag)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2019.11.35
    Win32 Version: 1.2019.11.35
    CodeBase: file:///C:/Users/.../XrmToolbox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2019.11.35
    Win32 Version: 1.2019.11.35
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 10.0.18362.239
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2019.11.35
    Win32 Version: 1.2019.11.35
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.14.0.832
    Win32 Version: 2.14.0.832
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/NuGet.Core.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.2.23222
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2019.11.27
    Win32 Version: 1.2019.11.27
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2019.11.27
    Win32 Version: 1.2019.11.27
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.37.948
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.37.958
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.37.948
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.30
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Ui.Styles
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.30
    CodeBase: file:///C:/Users/../Tools/XrmToolbox/Microsoft.Xrm.Tooling.Ui.Styles.DLL
----------------------------------------
Microsoft.Xrm.Tooling.CrmConnectControl
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.30
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/Microsoft.Xrm.Tooling.CrmConnectControl.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 5.2.4.0
    Win32 Version: 5.2.4.0
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.1.1.3
    Win32 Version: 4.6.26907.01
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/System.Net.Http.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/.../Tools/XrmToolbox/McTools.StopAdvertisement.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
AndyPopkin.BulkDeleteTool
    Assembly Version: 1.2018.10.20
    Win32 Version: 1.2018.10.20
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/ANDYPOPKIN.BULKDELETETOOL.DLL
----------------------------------------
BDK.XrmToolBox.StorageCleaner
    Assembly Version: 1.2019.7.1
    Win32 Version: 1.2019.7.1
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/BDK.XRMTOOLBOX.STORAGECLEANER.DLL
----------------------------------------
Colso.Xrm.DataTransporter
    Assembly Version: 1.2018.8.1
    Win32 Version: 1.2018.8.1
    CodeBase: file:///C:/USERS/xxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/COLSO.XRM.DATATRANSPORTER.DLL
----------------------------------------
DataImport
    Assembly Version: 1.2019.2.44
    Win32 Version: 1.2019.2.44
    CodeBase: file:///C:/USERS/xxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DATAIMPORT.DLL
----------------------------------------
Innofactor.Crm.XTB.Shuffle
    Assembly Version: 1.2019.11.8
    Win32 Version: 1.2019.11.8
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/INNOFACTOR.CRM.XTB.SHUFFLE.DLL
----------------------------------------
ITLec.RaiseYourVoice.D365RestorePoint
    Assembly Version: 1.2018.1118.6
    Win32 Version: 1.2018.1118.6
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/ITLEC.RAISEYOURVOICE.D365RESTOREPOINT.DLL
----------------------------------------
MarkMpn.Sql4Cds
    Assembly Version: 1.0.6.0
    Win32 Version: 1.0.6.0
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MARKMPN.SQL4CDS.DLL
----------------------------------------
Maverick.PCF.Builder
    Assembly Version: 2.2019.12.9
    Win32 Version: 2.2019.12.09
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MAVERICK.PCF.BUILDER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
    Assembly Version: 1.2018.4.1
    Win32 Version: 1.2018.4.1
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2019.6.12
    Win32 Version: 1.2019.6.12
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2019.5.1
    Win32 Version: 1.2019.5.1
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2019.5.12
    Win32 Version: 1.2019.5.12
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MscrmTools.WebresourcesManager
    Assembly Version: 2.2019.9.8
    Win32 Version: 2.2019.9.8
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
Norriq.XrmToolBox.Facilities.Core
    Assembly Version: 1.1.19281.3
    Win32 Version: 1.1.19281.3
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/NORRIQ.XRMTOOLBOX.FACILITIES.CORE.DLL
----------------------------------------
Norriq.XrmToolBox.Facilities.Tooling
    Assembly Version: 1.1.19281.3
    Win32 Version: 1.1.19281.3
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/NORRIQ.XRMTOOLBOX.FACILITIES.TOOLING.DLL
----------------------------------------
Rappen.XTB.BDU
    Assembly Version: 1.2019.12.1
    Win32 Version: 1.2019.12.001
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RAPPEN.XTB.BDU.DLL
----------------------------------------
Rappen.XTB.FXB
    Assembly Version: 1.2019.12.1
    Win32 Version: 1.2019.12.001
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RAPPEN.XTB.FXB.DLL
----------------------------------------
Rappen.XTB.PTV
    Assembly Version: 1.2019.12.1
    Win32 Version: 1.2019.12.001
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RAPPEN.XTB.PTV.DLL
----------------------------------------
RegisterPlugInSteps
    Assembly Version: 1.2018.12.10
    Win32 Version: 1.2018.12.10
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/REGISTERPLUGINSTEPS.DLL
----------------------------------------
Xrm.Sdk.PluginRegistration.Merged
    Assembly Version: 3.2019.7.1
    Win32 Version: 3.2019.07.001
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRM.SDK.PLUGINREGISTRATION.DLL
----------------------------------------
Xrm.Tools.CrmSvcUtilTS
    Assembly Version: 1.2018.7.1
    Win32 Version: 1.2018.7.1
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRM.TOOLS.CRMSVCUTILTS.DLL
----------------------------------------
XRMSolutionDependencyChecker
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRMSOLUTIONDEPENDENCYCHECKER.DLL
----------------------------------------
XrmToolbox.JavascriptValidator
    Assembly Version: 1.0.0.4
    Win32 Version: 1.0.0.4
    CodeBase: file:///C:/USERS/xxxxx/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRMTOOLBOX.JAVASCRIPTVALIDATOR.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MetadataViewProxies_d1e5e1e3-b4b7-463f-9a0b-d93d2c47a552
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data.Services.Client
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services.Client/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.Client.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
JourneyIntoCRM.XrmToolbox.ERDPlugin
    Assembly Version: 1.4.6.0
    Win32 Version: 1.4.6.0
    CodeBase: file:///C:/Users/xxxxx/AppData/Roaming/MscrmTools/XrmToolBox/Plugins/JourneyIntoCRM.XrmToolbox.ERDPlugin.dll
----------------------------------------
Carfup.XTBPlugins.DeltaStepsBetweenEnvironments
    Assembly Version: 1.2019.11.12
    Win32 Version: 1.2019.11.12
    CodeBase: file:///C:/Users/xxxxx/AppData/Roaming/MscrmTools/XrmToolBox/Plugins/Carfup.XTBPlugins.DeltaStepsBetweenEnvironments.dll
----------------------------------------
Carfup.XTBPlugins.DeltaAssemblyCRM
    Assembly Version: 1.2019.3.22
    Win32 Version: 1.2019.3.22
    CodeBase: file:///C:/Users/xxxxx/AppData/Roaming/MscrmTools/XrmToolBox/Plugins/Carfup.XTBPlugins.DeltaAssemblyCRM.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
Microsoft.VisualStudio.Diagnostics.ServiceModelSink
    Assembly Version: 4.0.0.0
    Win32 Version: 14.0.23107.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Diagnostics.ServiceModelSink/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.IdentityModel.Selectors
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

`

**Comment by rappen** [comment]
Just tried it, don't get the same issue...
Can you verify this?
Using Shuffle Builder 1.2020.3.25 and FetchXML Builder 1.2019.12.1

**Comment by rappen** [comment]
No more info from @imranakram, closing this issue, please reopen if more problems appear!
