### ISSUE TITLE
Error when pressing on the filter button in the lookup popup window with no value

### ISSUE THREAD

**Issue by Serjanya** [rappen/FetchXMLBuilder#320]
![image](https://user-images.githubusercontent.com/8789739/84266509-42c05380-ab2d-11ea-89da-130305e8d0f5.png)

Exception:
```
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Expected non-empty string. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040203
Message: Expected non-empty string.
StackTrace: 
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.MessageProcessor.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.InternalMessageDispatcher.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.ExternalMessageDispatcher.ExecuteInternal(IInProcessOrganizationServiceFactory serviceFactory, IPlatformMessage...).

```
Version: 1.2020.6.2

**Comment by rappen** [comment]
Hi @Serjanya 

I fail to reproduce this, and looking at the call stack, it seems like this is occuring in a plugin in your environment.
Can you verify if you have any plugins registered for RetrieveMultiple of systemuser (or all entities)?

**Comment by rappen** [comment]
Closing since I got no response. Feel free to reopen if necessary.
