### ISSUE TITLE
OData4 aggregates broken

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#365]
Super simple sample query:
```
<fetch aggregate='true' >
  <entity name='account' >
    <attribute name='address1_country' alias='Country' groupby='true' />
    <attribute name='accountid' alias='Count' aggregate='count' />
  </entity>
</fetch>
```
Executes flawlessly.

Corresponding OData4 query:
`https://jondough.crm4.dynamics.com/api/data/v9.1/accounts?$apply=groupby((address1_country),aggregate($count as Count))`

Nasty error:
```
{
    "error": {
        "code": "0x80040216",
        "message": "An unexpected error occurred.",
        "innererror": {
            "message": "An unexpected error occurred.",
            "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
            "stacktrace": "[see below]"
        }
    }
}
```

Stack Trace:
```
at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.RetrieveMultiple(QueryBase query, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, Guid appModuleId, Dictionary`2 optionalParameters)
at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.RetrieveMultiple(QueryBase query)
at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.RetrieveEdmEntityCollection(CrmODataExecutionContext context, String entityCollectionName, String castedEntityName, ODataQueryOptions queryOptions)
at Microsoft.Crm.Extensibility.OData.EntityController.GetEntitySetInternal(String entitySetName, String castedEntityName, CrmODataExecutionContext context, CrmEdmEntityObjectCollection crmEdmEntityObjectCollection, ODataQueryOptions queryOptions)
at Microsoft.Crm.Extensibility.OData.EntityController.GetEntitySetImplementation(String entitySetName)
at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass11_0`2.<InvokeActionAndLogMetric>b__0()
at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)
at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)
at lambda_method(Closure , Object , Object[] )
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

---
- Deployment: Online
- DB Version: 9.1.0.21347
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2020.7.3

**Comment by MarkMpn** [comment]
I'm pretty sure this is a CDS bug when grouping by an `address1_xxx` field. If you group by some other field, e.g.

```
https://jondough.crm4.dynamics.com/api/data/v9.1/accounts?$apply=groupby((telephone1),aggregate($count as Count))
```

it works as expected.
