### ISSUE TITLE
Commenting a condition throws an error in latest FXB. Commenting the raw XML still works.

### ISSUE THREAD

**Issue by mtnmuncher** [rappen/FetchXMLBuilder#408]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Cinteros.Xrm.FetchXmlBuilder.Controls.FetchXmlElementControlBase.InitializeFXB(Dictionary`2 collection, FetchXmlBuilder fetchXmlBuilder, TreeBuilderControl tree, TreeNode node)
   at Cinteros.Xrm.FetchXmlBuilder.Controls.commentControl..ctor(Dictionary`2 collection, TreeBuilderControl tree)
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.HandleNodeSelection(TreeNode node)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rappen** [comment]
Thanks for reporting, will push a fix ASAP!

**Comment by rappen** [comment]
Fix is now pushed and released. 🚀
