### ISSUE TITLE
Latest Version (1.2022.1.2) Does not work in XRMToolBox 

### ISSUE THREAD

**Issue by RugerSR762** [rappen/FetchXMLBuilder#621]
This was working fine until I just applied the update this morning.  I have the current version of XRMToolBox (v1.2021.12.53).  

Here is the error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: The local name for elements or attributes cannot be null or an empty string.
   at System.Xml.XmlElement..ctor(XmlName name, Boolean empty, XmlDocument doc)
   at System.Xml.XmlDocument.CreateElement(String prefix, String localName, String namespaceURI)
   at System.Xml.XmlDocument.CreateElement(String name)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.AddXmlNode(TreeNode currentNode, XmlNode parentXmlNode)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.Extensions.GetTooltip(TreeNode node)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetNodeTooltip(TreeNode node)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetWarnings(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.AddTreeViewNode(TreeNode parentnode, TreeNode node, XmlNode xmlNode, FetchXmlBuilder fxb, Boolean validate)
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.DisplayDefinition(XmlDocument fetchDoc)
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.ApplyCurrentSettings()
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by rappen** [comment]
Aouch - that's bad.
Can you add some more info?
Call when opening the tool?
What is the query fetchxml is used?
Something else?

**Comment by albert-halchanskiy** [comment]
Got the same error: 'The local name for elements or attributes cannot be null or empty' for all cloud crms. on-premise is ok

**Comment by rappen** [comment]
@albert-halchanskiy can I get a screenshot even? 🙏

**Comment by FabriceDB** [comment]
Got the same error. The starting of the app is good, but when i try to add a condition, i have the error 
![image](https://user-images.githubusercontent.com/90260514/149807691-3d3cdda5-cf5a-4b1a-8697-d8ae51500fd1.png)

**Comment by RugerSR762** [comment]
> Ah - I see it. Probably when opening with no fetchxml from last time and this connection. See this to go around this issue: https://www.screencast.com/t/5jxIE3RV
> 
> New release I hope bet out tonight!

Thank you for the very fast turnaround!
