### ISSUE TITLE
Object reference and a Nullable object error when opening tool and when trying to add attributes to entity

### ISSUE THREAD

**Issue by jxs0900** [rappen/FetchXMLBuilder#627]
FetchXMLBuilder version 1.2022.1.4

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.HandleNodeMenuClick(String ClickedTag)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![image](https://user-images.githubusercontent.com/8445048/150355124-9e5060f9-eeac-4c65-9082-febf5beaf829.png)
![image](https://user-images.githubusercontent.com/8445048/150355351-a51aed4c-2494-465d-9707-8fcba333f5d6.png)

**Comment by ali-shafique** [comment]
I am having exactly the same issue

**Comment by rappen** [comment]
Thanks @jxs0900 and @ali-shafique 

I see the same error for `all-attributes`, so currently this done not work.
It will be fixed.
Until the fix is released, you can use it **without** the `all-attributes` - it works the same way (for simply queries).

See:
![image](https://user-images.githubusercontent.com/2572253/150482071-e9b93896-51bb-4276-a284-50392c22701e.png)
