### ISSUE TITLE
Nullable object must have a value

### ISSUE THREAD

**Issue by bkwoka** [rappen/FetchXMLBuilder#631]
Hi.

I have a problem with FetchXml Builder.
Whenever I try to add an attribute I get an error

![image](https://user-images.githubusercontent.com/52539097/151672372-95b956d2-7914-4c28-b04b-8aadfd7ecc8d.png)
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.Validations.GetWarning(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetWarnings(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetWarnings(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetWarnings(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetNodeText(TreeNode node, FetchXmlBuilder fxb, Boolean validate)
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.CtrlSaved(Object sender, SaveEventArgs e)
   at Cinteros.Xrm.FetchXmlBuilder.Controls.FetchXmlElementControlBase.SaveInternal(Boolean keyPress)
   at Cinteros.Xrm.FetchXmlBuilder.Controls.FetchXmlElementControlBase.Save(Boolean keyPress)
   at Cinteros.Xrm.XmlEditorUtils.ControlUtils.ComboBoxEventHandler.OnSelectedIndexChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rappen** [comment]
Thanks for reporting.
Somehow the problem is still here, for some reason.
I get the error when I just tried it now, but not when I try again...
I have to look into this!
