### ISSUE TITLE
Still getting "Nullable object must have a value" error after installing 1.2022.1.5

### ISSUE THREAD

**Issue by jimboulais** [rappen/FetchXMLBuilder#634]
![image](https://user-images.githubusercontent.com/83228462/151857086-909f5dc7-1f40-4e3e-9c7a-1145706035f1.png)

Full error  text:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.Validations.GetWarning(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetWarnings(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetWarnings(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetWarnings(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.SetWarnings(TreeNode node, FetchXmlBuilder fxb)
   at Cinteros.Xrm.FetchXmlBuilder.AppCode.TreeNodeHelper.AddTreeViewNode(TreeNode parentnode, TreeNode node, XmlNode xmlNode, FetchXmlBuilder fxb, Boolean validate)
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.DisplayDefinition(XmlDocument fetchDoc)
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.ApplyCurrentSettings()
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by rappen** [comment]
Hm. I can't get the error...

- Does the query "seem" ok to you?
- You expect a Warning?
- Have a good connection?
- Get the error just opening FXB?
- What's the last action you did?

**Comment by jimboulais** [comment]
1.  Just a simple query to illustrate the point, if I click on the Continue button in the error it eventually gives the results
2.  Wasn't really expecting anything (especially not an error message)
3.  Yes (see #1)
4.  Yes, if I close out and go back in, I get the error upon opening FXB
5.  Added the filter

Note - we were seeing this in 1.2022.1.4 and reverted back to the Oct 2021 release (doesn't have new "tree nodes") and did not have any problems using that dll.

**Comment by rappen** [comment]
Thanks for the info 🙏

It helps a lot (or a bit) if we get versions, like you get when you create issues from XTB tool:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/2572253/151864208-393aca89-5176-4c6b-a60c-19c1fe2990d8.png">

I'm continuing to look for the error.

**Comment by jimboulais** [comment]
---
- Deployment: OnPremise
- DB Version: 8.1.0.359
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53
- Tool Version: 1.2022.1.5

**Comment by rappen** [comment]
Ok, most likely a DB version issue.
I don't have that version to test 😕
The column `new_licensetype` - is it an picklist (also known as Options, Choice, Choices...)?

**Comment by jimboulais** [comment]
These are custom tables added to CRM.  And yes, the column new_licensetype is in the picklist.  Also note, it works fine with a prior FXB release prior to the tree node changes.  We are upgrading to CRM version 9.X this coming weekend, but have never had any issues with the current one.

![image](https://user-images.githubusercontent.com/83228462/151866894-44e200aa-eba1-4903-b93b-101801068d8c.png)

**Comment by rappen** [comment]
Got it. We're getting closer...
The newest version of FXB have new features, and that probably crash with older version of the DB.
I will fix this 💪

**Comment by rappen** [comment]
Would you like to test an unofficial version?
I think I have it now...
Send me an email to jonas at jonasr.app and I'll send it to you.

**Comment by jimboulais** [comment]
I did send an email - got an automatic reply...

**Comment by JunbinDuan** [comment]
@rappen sent an email to you from my email address JunbinDuan@yahoo.ca. Thanks for the great effort and contribution.

**Comment by rappen** [comment]
Ok, I'll send it to that too.

**Comment by JunbinDuan** [comment]
I cannot download. It shows the zip file has been removed.

**Comment by rappen** [comment]
Ok, send a new email with a link instead.

**Comment by jimboulais** [comment]
Downloaded, installed and quick testing is showing no errors!  Thanx for the fix

**Comment by JunbinDuan** [comment]
Works. Thanks for the quick fix!

**Comment by rappen** [comment]
Awesome!
An official is coming soon...
