### ISSUE TITLE
FetchXML crashes when selecting attributes

### ISSUE THREAD

**Issue by jxs0900** [rappen/FetchXMLBuilder#684]
![image](https://user-images.githubusercontent.com/8445048/160648852-004e8022-9286-4688-a11e-28a95f88a2ef.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Cinteros.Xrm.FetchXmlBuilder.Forms.SelectAttributesDialog.GenerateAllItems(List`1 attributes, List`1 selectedAttributes)
   at Cinteros.Xrm.FetchXmlBuilder.Forms.SelectAttributesDialog..ctor(List`1 attributes, List`1 selectedAttributes)
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.SelectAttributes()
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.TreeBuilderControl.HandleNodeMenuClick(String ClickedTag)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rappen** [comment]
Hi - which version of DB you have?
Do you also know in which version of FXB it latest it worked?

**Comment by rappen** [comment]
Closing due to no response.
Please reopen if you have more info.
