### ISSUE TITLE
Error when clicking Select Attributes

### ISSUE THREAD

**Issue by CJatBH** [rappen/FetchXMLBuilder#777]
After clicking on "Select Attributes" I receive an error "Nullable object must have a value".  I am on CRM 2015 and am using the latest release of FXB.

System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Rappen.XTB.FetchXmlBuilder.Forms.SelectAttributesDialog.GenerateAllItems(List`1 attributes, List`1 selectedAttributes)
   at Rappen.XTB.FetchXmlBuilder.Forms.SelectAttributesDialog..ctor(List`1 attributes, List`1 selectedAttributes)
   at Rappen.XTB.FetchXmlBuilder.DockControls.TreeBuilderControl.SelectAttributes()
   at Rappen.XTB.FetchXmlBuilder.FetchXmlBuilder.<>c__DisplayClass73_0.<LoadEntityDetails>b__1(RunWorkerCompletedEventArgs completedargs)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

![image](https://user-images.githubusercontent.com/112718259/188197802-eb121b7a-8fcc-4704-8d2a-e21ea5edd264.png)

**Comment by rappen** [comment]
Thanks for the report!
I'll investigate what metadata problem we have for CRM 2015.
Can you say which exact version of the Dynamics? I guess 7.0.x.x something...?

Note - it does not look like latest version in your screenshot, it should look like this:

![image](https://user-images.githubusercontent.com/2572253/188265056-13b2c72b-7fbb-427f-8e02-4a9ff6edf86f.png)

See the modern error message popup, and see the rebranded namespaces (start with "Rappen" instead of old "Cinteros")

**Comment by CJatBH** [comment]
I just made sure I have the latest version of XrmToolBox (1.2022.2.54) and the latest version of FXB (1.2022.8).  Below is the updated error message, but the popup style has not changed.

************** Exception Text **************
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Rappen.XTB.FetchXmlBuilder.Forms.SelectAttributesDialog.GenerateAllItems(List`1 attributes, List`1 selectedAttributes)
   at Rappen.XTB.FetchXmlBuilder.Forms.SelectAttributesDialog..ctor(List`1 attributes, List`1 selectedAttributes)
   at Rappen.XTB.FetchXmlBuilder.DockControls.TreeBuilderControl.SelectAttributes()
   at Rappen.XTB.FetchXmlBuilder.FetchXmlBuilder.<>c__DisplayClass73_0.<LoadEntityDetails>b__1(RunWorkerCompletedEventArgs completedargs)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by rappen** [comment]
That's, I will continue investigating.
May you say which version of Dynamics 365 DB you have?

(PS, latest version of XTB is 1.2022.5.56 from this spring - I always suggest to update to latest :)

**Comment by CJatBH** [comment]
I just updated to the latest XTB version 1.2022.5.56 and still face the issue.  I am not sure why it didn't update earlier.

I am on Microsoft Dynamics® CRM 2015 (7.0.3.152) (DB 7.0.3.152).

**Comment by rappen** [comment]
It's hard to test in CRM 2015 unfortually for me...

Can you test the different options of these checkboxes in this green highlighted?

![image](https://user-images.githubusercontent.com/2572253/189123473-e560b59c-9756-455f-a8ad-b584b6eff26d.png)

Can you get the attributes if you just add one attribute, like this?

![image](https://user-images.githubusercontent.com/2572253/189123760-90feee50-171f-4d4b-98fb-fcf0c38583e3.png)

**Comment by CJatBH** [comment]
I have both options unchecked otherwise I can't get any entities.  With both boxes unchecked I can add fields one at a time.

**Comment by rappen** [comment]
Long time... 
I'm just wondering if you still have this issue?

**Comment by CJatBH** [comment]
This is no longer happening.  Thanks so much!
