### ISSUE TITLE
Latest Version of XRM Toolbox Fails to Open Due to FetchXML Builder?

### ISSUE THREAD

**Issue by blob150** [rappen/FetchXMLBuilder#832]
I just updated my XRM Toolbox to version 1.2022.11.59.  Now when I try to open it I get the message below.

Could not load file or assembly 'CINTEROS.XRM.FETCHXMLBUILDER.DLL' or one of its dependencies. An attempt was made to load a program with an incorrect format.

at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.<>c.<CreateManifest>b__4_2(String f)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.CreateManifest(IReadOnlyCollection`1 composition, DirectoryCatalog catalogue)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.LoadParts(Boolean isRetry)
   at XrmToolBox.PluginManagerExtended.RescanIfRequired()
   at XrmToolBox.PluginManagerExtended.Initialize(Form parentForm)
   at XrmToolBox.New.PluginsForm..ctor()
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)

**Comment by rappen** [comment]
See reason/solution: https://github.com/MscrmTools/XrmToolBox/issues/1093
Error is shown in "XrmToolBox", not in "XRM Toolbox" btw.... ;)
