### ISSUE TITLE
Claims error when querying sharepointdocument entity logged in with clientid and secret

### ISSUE THREAD

**Issue by jeffmacfie** [rappen/FetchXMLBuilder#910]
I am sure the probably has to do with Sharepoint security or application api permissions.  I have granted access on both sides but when i try to query the sharepointdocument entity I get the following error.  Just wanted to let you know.

At least 1 Claim must not be NULL, current claims are : nameid=;nii=urn:federation:microsoftonline

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.RetrieveMultiple(QueryBase query)
   at Rappen.XTB.FetchXmlBuilder.FetchXmlBuilder.RetrieveMultiple(QueryBase query, Boolean allrecords)
   at Rappen.XTB.FetchXmlBuilder.FetchXmlBuilder.<>c__DisplayClass121_0.<RetrieveMultiple>b__0(BackgroundWorker worker, DoWorkEventArgs eventargs)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by rappen** [comment]
Thanks for this info!

I'll close this now (very late though...), please reopen if we should do anything about it.
